### ISSUE TITLE
[suggestion] solid role color over display names

### ISSUE THREAD

**Issue by ehylo** [GriefMoDz/smart-typers#6]
Add another option to display the names top role color instead of the gradient, I don't really like the gradient and would rather just have another option for it to be one color of the role they have. I understand if this is dumb and you won't add it but I hope you do anyway!

**Comment by GriefMoDz** [comment]
Thanks for the suggestion! However, I'm afraid I've decided not to introduce this as a new feature seeing as "Role Color Everywhere" already provides this sort of functionality. You're more than welcome to clone it from this link [here](https://github.com/powercord-community/rolecolor-everywhere).

From there you'll be able to jump right into your user settings, select the "Role Color Everywhere" tab, and toggle the "Typing Indicator" setting that magically sets the display names of typing users to their respective role color.

Hopefully that helps! And please feel free to let me know if you're having problems or otherwise just need to ask me any questions - my Discord is: `M|-|4r13y ツ#1051`.

I'll now be closing this issue. Cheers!

**Comment by ehylo** [comment]
Ok thanks for the response but I don't want to use that plugin so rip, thanks anyways
